auto: false
server: false
lsi: false
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
paginate: 10
exclude: ["Rakefile", "LICENSE.txt", "CNAME"]
title: Michael Ebens
url: http://nova-fusion.com
github_user: BlackBulletIV
game_dir: games
