auto: false
server: false
lsi: false
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
paginate: 10
exclude: ["Rakefile", "LICENSE.txt", "CNAME"]
title: Michael Ebens
url: http://nova-fusion.com
github_user: BlackBulletIV
projects:
  strong:
    version: 1.0.2
    docs: wiki
    description: A small Lua library which greatly enhances strings.
  "amfphp-toolbox":
    title: AMFPHP Toolbox
    version: 2.1.1
    description: An ActionScript library to help you get more done with AMFPHP.
  "enhanced-lua.tmbundle":
    description: "This is my version of the Lua TextMate bundle. I've taken it and added support for the libraries I use a lot in Lua. These are MiddleClass, Telescope, and the Love2D engine."
  SOSConnection:
    version: 1.0.1
    description: A class that makes using SOS max more straight forward.
  "unix-utils":
    title: Unix Utils
    description: Project for the utility commands for the terminal I have/might/will make.
  vault:
    title: Vault
    version: "1.0"
    description: "A small data storage library for Love2D, which allows you to save and retrieve data in native Lua data types."
  "middleclass-extensions":
    title: MiddleClass Extensions
    version: "1.0"
    description: My extensions to MiddleClass.
  closureclass:
    title: ClosureClass
    description: "A Lua object-orientation library based on MiddleClass, except using the closure approach. Not fit for production!"
  "as3-benchmarking":
    title: "AS3 Benchmarking"
    version: "0.1"
    description: A few experimental classes for benchmarking in AS3.
music:
  -
    title: A Day in Life
    date: "July 10, 2011"
    length: "1:23"
    video: ARDWCzmNoy0
    file: A Day in Life.mp3
    description: "A quick and simple tune I put together in about an hour and a half; pretty repetive base tune, sounds pretty fit for a time lapse (hence the title). Instruments are organ, strings, and a custom-tuned electronic bell."
  -
    title: Run
    date: "June 8, 2011"
    length: "1:49"
    video: xdgI1tJca1A
    file: Run.mp3
    description: "Fast paced, giving the sense of running. Piano, strings, a synth instrument, and a bass guitar are the instruments."
  -
    title: The Mountain
    date: "May 28, 2011"
    length: "2:16"
    video: PrGvRJLOYHU
    file: The Mountain.mp3
    description: "Slow and reflective, this song gives a feel of a long climb while reflecting on what has been done. Strings, piano, and flute, are the instruments."
  -
    title: Looking Back
    date: "April 17, 2011"
    length: "1:20"
    video: Fvhsfsgc_Ck
    file: Looking Back.mp3
    description: "Slow(ish) and reflective, possibly picturing looking back over the path travelled. Strings and flute are the instruments. Also, this song was made to be looped."

